# Generated by Django 2.0.3 on 2018-06-19 21:13

from django.db import migrations, models
import django.db.models.manager
import django_prices.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0064_productvariant_handle_stock'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='product',
            managers=[
                ('tagObjects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='product_id',
            field=models.CharField(default=123, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.CharField(default=123, max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=django_prices.models.MoneyField(currency='ISK', decimal_places=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='cost_price',
            field=django_prices.models.MoneyField(blank=True, currency='ISK', decimal_places=0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='price_override',
            field=django_prices.models.MoneyField(blank=True, currency='ISK', decimal_places=0, max_digits=12, null=True),
        ),
    ]
