# Generated by Django 2.0.3 on 2018-06-19 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('greinar', '0003_auto_20180619_2113'),
        ('product', '0065_auto_20180619_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Greinar',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='greinar.greinar'),
            preserve_default=False,
        ),
    ]
