# Generated by Django 2.0.3 on 2018-06-20 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greinar', '0005_remove_greinar_greinar_id'),
        ('product', '0066_product_greinar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Greinar',
        ),
        migrations.AddField(
            model_name='product',
            name='Greinar',
            field=models.ManyToManyField(blank=True, related_name='greinar', to='greinar.greinar'),
        ),
    ]
