# Generated by Django 2.0.3 on 2018-06-22 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0070_auto_20180621_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='attributechoicevalue',
            name='color',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
