# Generated by Django 2.0.3 on 2018-06-22 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0071_attributechoicevalue_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attributechoicevalue',
            old_name='color',
            new_name='litur',
        ),
        migrations.AddField(
            model_name='productattribute',
            name='litur',
            field=models.BooleanField(default=False),
        ),
    ]
