# Generated by Django 2.0.3 on 2018-06-22 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0073_auto_20180622_0927'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attributechoicevalue',
            unique_together={('name', 'attribute', 'litur')},
        ),
    ]
