# Generated by Django 2.0.3 on 2018-06-22 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0076_auto_20180622_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attributechoicevalue',
            name='litur',
            field=models.CharField(default='#ffffff', max_length=100),
        ),
    ]
