# Generated by Django 2.0.3 on 2018-06-22 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0077_auto_20180622_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attributechoicevalue',
            name='litur',
            field=models.CharField(max_length=100),
        ),
    ]
