# Generated by Django 2.0.3 on 2018-06-22 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0078_auto_20180622_1147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attributechoicevalue',
            name='litur',
        ),
    ]
