# Generated by Django 2.0.3 on 2018-06-22 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0079_remove_attributechoicevalue_litur'),
    ]

    operations = [
        migrations.AddField(
            model_name='attributechoicevalue',
            name='litur',
            field=models.CharField(default='#ffffff', max_length=100),
        ),
    ]
