# Generated by Django 2.0.3 on 2018-06-22 13:34

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0080_attributechoicevalue_litur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attributechoicevalue',
            name='litur',
            field=colorfield.fields.ColorField(default='#FFFFFF', max_length=18),
        ),
    ]
