# Generated by Django 2.0.3 on 2018-06-22 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0081_auto_20180622_1334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attributechoicevalue',
            name='litur',
        ),
    ]
