# Generated by Django 2.0.3 on 2018-06-19 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('greinar', '0002_auto_20180321_0417'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='greinar',
            name='available_on',
        ),
        migrations.RemoveField(
            model_name='greinar',
            name='created',
        ),
        migrations.RemoveField(
            model_name='greinar',
            name='is_visible',
        ),
    ]
