# Generated by Django 2.0.3 on 2018-06-19 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('greinar', '0004_greinar_greinar_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='greinar',
            name='Greinar_id',
        ),
    ]
