# Generated by Django 2.0.3 on 2018-06-20 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greinar', '0005_remove_greinar_greinar_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='greinar',
            name='image',
            field=models.ImageField(blank=True, upload_to='greinar_myndir/'),
        ),
        migrations.AlterField(
            model_name='greinar',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
    ]
