# Generated by Django 2.0.3 on 2018-06-20 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('greinar', '0006_auto_20180620_2050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='greinar',
            name='image',
        ),
    ]
