# Generated by Django 2.0.3 on 2018-06-20 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greinar', '0007_remove_greinar_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='greinar',
            name='slug',
            field=models.SlugField(max_length=100, null=True, unique=True),
        ),
    ]
