# Generated by Django 2.0.3 on 2018-06-20 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greinar', '0008_auto_20180620_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='greinar',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='greinar',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
