# Generated by Django 2.0.3 on 2018-06-20 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greinar', '0010_greinar_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='greinar',
            name='image',
            field=models.ImageField(blank=True, default=0, upload_to='greinar_myndir/'),
            preserve_default=False,
        ),
    ]
