# Generated by Django 2.0.3 on 2018-06-20 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('greinar', '0011_auto_20180620_2119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='greinar',
            name='image',
        ),
    ]
