# Generated by Django 2.0.3 on 2018-06-20 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greinar', '0012_remove_greinar_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='greinar',
            name='image',
            field=models.ImageField(default='greinar_myndir/logo.png', upload_to='greinar_myndir/'),
        ),
    ]
