# Generated by Django 2.0.3 on 2018-06-20 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('greinar', '0013_greinar_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='greinar',
            name='image',
        ),
    ]
