# Generated by Django 2.0.3 on 2018-06-20 21:50

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('greinar', '0014_remove_greinar_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='greinar',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='greinar_myndir'),
        ),
    ]
