# Generated by Django 2.0.3 on 2018-06-20 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greinar', '0018_remove_greinar_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='greinar',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='greinar_myndir'),
        ),
    ]
