# Generated by Django 2.0.3 on 2018-06-20 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greinar', '0019_greinar_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='greinar',
            name='picture',
            field=models.FileField(blank=True, null=True, upload_to='greinar_myndir'),
        ),
    ]
