# Generated by Django 2.0.3 on 2018-06-21 00:07

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('greinar', '0020_auto_20180620_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='greinar',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
