# Generated by Django 2.0.3 on 2018-06-21 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greinar', '0021_auto_20180621_0007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='greinar',
            name='picture',
        ),
        migrations.AddField(
            model_name='greinar',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='greinar_myndir'),
        ),
    ]
