# Generated by Django 2.0.3 on 2018-06-21 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greinar', '0023_auto_20180621_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='greinar',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='greinar_myndir/%Y/%m/%D/'),
        ),
    ]
