# Generated by Django 2.0.3 on 2018-06-21 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greinar', '0024_auto_20180621_0028'),
    ]

    operations = [
        migrations.AddField(
            model_name='greinar',
            name='ok',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
