# Generated by Django 2.0.3 on 2018-06-21 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('greinar', '0025_greinar_ok'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='greinar',
            name='ok',
        ),
    ]
