# Generated by Django 2.0.3 on 2018-06-21 08:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('greinar', '0026_remove_greinar_ok'),
    ]

    operations = [
        migrations.AddField(
            model_name='greinar',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='greinar',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='greinamyndir/%Y/%m/%D/'),
        ),
    ]
