# Generated by Django 2.0.3 on 2018-06-21 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greinar', '0027_auto_20180621_0847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='greinar',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='greinamyndir/%Y/%m/'),
        ),
    ]
