# Generated by Django 2.0.3 on 2018-06-21 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greinar', '0028_auto_20180621_0930'),
    ]

    operations = [
        migrations.AddField(
            model_name='greinar',
            name='titletext',
            field=models.CharField(default='title', max_length=200),
            preserve_default=False,
        ),
    ]
