# Generated by Django 2.0.3 on 2018-06-21 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greinar', '0031_auto_20180621_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='greinar',
            name='image_size',
            field=models.CharField(choices=[('lítil', 'Lítil'), ('stór', 'Stór')], default=1, max_length=20),
        ),
    ]
